.gitignore, cnt.go, cnt_test.go, hack/check.sh, lex.go, lex_test.go, node.go, parse.go, parse_test.go, spec.org, testfiles/ex1.cnt, tree_test.go
- Added a simple grammar specification in file spec.org
- Implementation of parser
WIP
=> WIP of recursive descent parser

README.md, cmd/cnt/cli.go, cmd/cnt/ex1.cnt, cmd/cnt/example.cnt, cmd/cnt/main.go, cmd/cnt/rpc.go, cnt.go, cnt_test.go, design.org, lex.go, lex_test.go, node.go, parse.go, parse_test.go, rfork.go, spec.org, tree.go, tree_test.go, util.go
- Finish implementation of rfork using a client-server unix socket implementation for inter-namespaces communications.
- Adds a simple example to execute the rc inside a busybox space.
=> Execution engine

Makefile, README.md, cmd.go, cmd/nash/Makefile, cmd/nash/cli.go, cmd/nash/main.go, cmd_test.go, contrib/images/stali/build.sh, examples/init, itemtype_string.go, lex.go, lex_test.go, nash.go, nash_test.go, node.go, nodetype_string.go, parse.go, parse_test.go, parse_util_test.go, spec.ebnf
Support for functions and lambdas.
Example:
```sh
fn gob() {
go build -v
}
fn gcd(gorepo) {
cd $GOPATH+"/src/"+$gorepo
}
gcd("github.com/NeowayLabs/nash")
gob()
```
=> Function declarion and invocation

cmd/nash/cli.go, error.go, lex.go, lex_test.go, parse.go, parse_test.go
=> Add support for multiline list assignment

lex.go, lex_test.go, parse.go
=> Add quoted strings and variables to list

lex.go, lex_test.go, parse.go, spec.ebnf
=> Fix issue with pipes and redirections. 

node.go, parse.go, parse_regression_test.go, parse_util_test.go
=> Fix issue39 parser problem

cmd/nash/main.go
=> Add -c POSIX option

lex_regression_test.go, nash.go, nash_test.go, parse.go, parse_regression_test.go
=> Fix parsing of pipes.

examples/init, itemtype_string.go, lex.go, lex_test.go, nash.go, nash_test.go, node.go, nodetype_string.go, parse.go, parse_test.go, parse_util_test.go
=> Add for loop

README.md, lex.go, nash.go, nash_test.go
=> Add special meaning to IFS variable to help word spliting

cmd/nash/cli.go, cmd/nash/completer.go, lex_test.go
=> Improve autocomplete

.gitignore, argtype_string.go, cmd.go, itemtype_string.go, lex.go, lex_regression_test.go, lex_test.go, nash.go, nash_test.go, node.go, parse.go, parse_test.go
=> Variable indexing

nash.go
Use a more basic approach. No job control.
Nash handle SIGINT only to break loops from the shell, the termination of childs in the same process group are handled by kernel.
=> Update signal handling

nash.go
=> Set SHELL to value in /proc/self/exe. Closes #36

cmd.go, nash.go, nash_regression_test.go, nash_test.go, parser/parse_regression_test.go, parser/parse_test.go, scanner/lex_regression_test.go
Fix of this bug requires refactor of pipes implementation.
Closes #68
=> WIP: Pipes and redirection

ast/node.go, ast/nodetype_string.go, internal/sh/shell.go, internal/sh/shell_test.go, parser/parse.go, parser/parse_test.go, parser/parse_util_test.go, scanner/lex.go, scanner/lex_test.go, spec.ebnf
=> Remote showenv keyword. 

ast/node.go, internal/sh/shell_test.go, parser/parse.go, scanner/examples_test.go, scanner/lex.go, scanner/lex_regression_test.go, scanner/lex_test.go, token/token.go
=> Improve scanner/lexer error messages

ast/tree.go, errors/error.go, parser/parse.go, parser/parse_fmt_test.go, parser/parse_regression_test.go, parser/parse_test.go, scanner/lex.go, scanner/lex_regression_test.go, scanner/lex_test.go
=> Fix list assignment. 

parser/parse.go, parser/parse_regression_test.go
=> Correctly parse imports. 

ast/node.go, ast/node_args.go, ast/node_fmt.go, ast/nodetype_string.go, ast/tree.go, ast/tree_test.go, internal/sh/shell.go, parser/parse.go, parser/parse_fmt_test.go, parser/parse_regression_test.go, parser/parse_test.go, scanner/lex.go, token/token.go
=> Improve the code formatting

internal/sh/shell_test.go
=> add timeout to synchronize with external SIGINT

ast/node_fmt.go, parser/parse_fmt_test.go
=> fmt: Solve redirection formatting of pipes and backslashes

internal/sh/shell.go, internal/sh/shell_test.go
=> Fix redirection not working with concat expr

parser/parse.go, spec.ebnf
=> Fix invocaton of fn from variables. 

ast/node_fmt.go, parser/parse_fmt_test.go
=> ast: Fix fmt out of bounds

internal/sh/shell.go, internal/sh/shell_test.go, nash.go, nash_test.go
=> Add nash.Setvar and nash.Getvar

parser/parse.go
Add missing linenum/col to some parser location
Closes #136
=> Fix error messages. 

internal/sh/shell.go
=> Fix windows build

README.md, examples/args.sh
Just add to the docs how to use the command line args. Found it on the source code pretty fast though...great code ;-)
=> Add docs and example to work with cmd line args

ast/node.go, ast/node_fmt.go, internal/sh/shell.go, parser/parse.go, parser/parse_regression_test.go, parser/parse_test.go
Required to handle more advanced assignments (like multiple return functions).
=> Little refactor of parser

ast/node_fmt.go, ast/node_fmt_test.go
=> fix formatting of carrige return

Dockerfile
@vitorarins Had you set up automatic build of image in the official docker hub? Or I'll need to push the image manually?
=> update dockerfile to go1.8

parser/parse.go
=> fix parser err msg

internal/sh/shell.go, internal/sh/shell_test.go
=> Remove override of StdErr in pipe commands

internal/sh/builtin/format.go, internal/sh/builtin/format_test.go, internal/sh/builtin/print.go, internal/sh/builtin/print_test.go
Although the problem does not seem to be related to format.
=> Odd behavior for format

cmd/nash/cli.go, cmd/nash/main.go
=> Sets NASHPATH in every nash interpreter mode

internal/sh/shell.go, internal/sh/shell_test.go
The redirection tests sucks.. I'll improve that
Closes #216
=> Redirection to file should truncate when possible

.gitignore, Makefile, README.md, cmd/nash/Makefile, hack/releaser.sh
Shifting from Full manual to Semi Auto =P. Not fully auto yet.
=> Add releaser

cmd/nash/cli.go, cmd/nash/completer.go, internal/sh/builtin.go, internal/sh/builtin/exit.go, internal/sh/builtin/loader.go, internal/sh/builtin/split.go, internal/sh/builtin/testdata/splitfunc.sh, internal/sh/fncall.go, internal/sh/fndef.go, internal/sh/functions_test.go, internal/sh/shell.go, internal/sh/shell_test.go, nash.go, sh/obj.go, sh/shell.go
Just reproducing know problems for now
=> Fix closures bugs

internal/sh/shell_test.go, parser/parse.go, parser/parse_test.go
=> Add missing syntax for passing variable funcall as argument

README.md
Dudes, I'm think this is useful.
Make sense at section "Installation" ?
=> Added nashfmt install

hack/check.sh, stdlib/fmt_example.sh, stdlib/io.sh, stdlib/io_example.sh, stdlib/io_test.sh
As I talked with @vitorarins I was not very happy with the fmt package, I copied from golang but it really did not seem to be a good fit to what is inside the package.
=> Rename fmt to io

cmd/nash/cli.go, cmd/nash/main.go
I enjoy always using .sh but it did not worked on init, it seemed consistent to support this =)
=> Add support to init.sh

internal/sh/builtin/split_test.go
=> Add tests to guarantee that split by func dont panic

.travis.yml, hack/releaser.sh, stdbin/write/fd.go, stdbin/write/fd_windows.go
I'm not sure if other OSes will have /dev/stdout as linux, but it seemed that the outlier is windows =P. So I tried to fix the write stdbin on these other platforms. I also added the release procedure to the CI to avoid this is the future =)
=> Fix release generation for all OSs

.travis.yml, hack/releaser.sh
- Add CGO_ENABLED depending on the os; 
- Nashfmt'd the script (sorry).
=> Fix Releaser script

tests/cfg.go
I forgot to push this on the previous branch =P
=> Check error right after working dir call
