madlambda/nash

cmd.go, itemtype_string.go, lex.go, lex_test.go, nash.go, nash_test.go, node.go, nodetype_string.go, parse.go, parse_test.go, parse_util_test.go
Usage is like Posix and pipe execution can be assigned to variables much like commands, using the '<=' operator.
```sh
λ> cat /etc/passwd | grep root
λ> ipaddr <= ip a | grep inet | grep global | awk "{print $2}" | cut -d / -f1
λ> echo $ipaddr
10.137.2.14
```
=> Implementation of pipes

cmd/nash/cli.go, itemtype_string.go, lex.go, lex_test.go, nash.go, nash_test.go, node.go, nodetype_string.go, parse.go, parse_test.go, parse_util_test.go, spec.ebnf
Add return statement to function declaration.
Not it's possible to:
```sh
fn getdirs(path) {
directories <= ls $path
return $directories
}
dirs <= getdirs("/")
echo $dirs
```
Output:
```
amd64
bin
boot
data
dev
etc
home
ipfs
ipns
lib
lib64
lost+found
mnt
n
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
```
=> [WIP] Function return statement

cmd/nash/main.go, nash.go, nash_linux_test.go, nash_test.go
Create a separate API to create sub shells to avoid issues with locking and signal handling.
Closes #59
=> Separate API for sub shells

nash.go, nash_test.go, node.go, parse.go, spec.ebnf
The builtin keyword was added (much like rc builtin) to force the use of a builtin keyword when overrided by bindfn. Now bindfn have scope in the same way as variables.
Then, to override "cd", the *only* way to avoid an infinite loop now is using the "builtin":
```
fn cd(path) {
builtin cd $path
}
bindfn cd cd
```
=> Add builtin keyword

README.md, ast/node.go, errors/error.go, internal/sh/shell_test.go, parser/parse.go, parser/parse_regression_test.go, parser/parse_test.go, scanner/lex_test.go, spec.ebnf
Added support for multiline command execution.
Usage examples:
```sh
λ> (aws ec2 attach-internet-gateway	
--internet-gateway-id $igwid
--vpc-id $vpcid)
```
```sh
λ> (
aws ec2 run-instances
--image-id ami-xxxxxxxx
--count 1
--instance-type t1.micro
--key-name MyKeyPair
--security-groups my-sg
| jq ".Instances[0].InstanceId"
)
```
It could be used in every place a command is expected. In command assignment, for example:
```sh
λ> instanceId <= (
aws ec2 run-instances
--image-id ami-xxxxxxxx
--count 1
--instance-type t1.micro
--key-name MyKeyPair
--security-groups my-sg
| jq ".Instances[0].InstanceId"
)
λ> echo $instanceId
```
Closes #90 
@lborguetti
=> Add support for multiline commands and assignments

ast/node_fmt.go
Closes #104 
Now, the code below:
```sh
fn aws_instance_create(imgid, kname, secgrps, type, privip, subnetid) {
instid <= (
aws ec2 run-instances
--image-id
$imgid --count 1 --key-name kubernetes --security-group-ids $secgrps --instance-type $type --private-ip-address $privip --subnet-id $subnetid
--associate-public-ip-address |
jq -r ".Instances[].InstanceId"
)
}
```
is formatted as:
```sh
fn aws_instance_create(imgid, kname, secgrps, type, privip, subnetid) {
instid <= (
aws ec2 run-instances
--image-id $imgid
--count 1
--key-name kubernetes
--security-group-ids $secgrps
--instance-type $type
--private-ip-address $privip
--subnet-id $subnetid
--associate-public-ip-address
|
jq -r ".Instances[].InstanceId"
)
}
```
=> Fix panic when formatting pipes

parser/parse.go, parser/parse_regression_test.go
The last refactor of parser introduced a bug because the old scanner/lexer was much more aware of the grammar and delivered only high level tokens to parser. But current lexer do not disambiguate tokens. 
The bug was a missing handling of valid tokens for command arguments.
Closes #108
=> parser: Fix a bug in parser not allowing keyword names as command arguments.

cmd/nashfmt/main.go, internal/sh/shell_test.go, parser/parse.go, parser/parse_regression_test.go, parser/parse_test.go, scanner/lex.go, scanner/lex_test.go
- Forbid use of function call in pipelines
The command below now throws a correct error:
`echo "test test" | replace(" ", "|")`
before this commit, the command above returns a `UnfinishedCmdError` entering the `cli` in multi-line state.
- Improve the error for invalid sintaxes (Closes #123)
=> Improve the parser on several corner cases

README.md, internal/sh/shell.go, internal/sh/shell_test.go, internal/sh/split.go, internal/sh/split_test.go
The `IFS` special variable was removed to increase script reliability. For now, if you want to split variable
content or command output into a list you can use the `split` builtin function.
content = "some thing"
list <= split($content, " ")
echo $list[0] $list[1]
Closes #128 
Signed-off-by: Tiago <tiago.natel@neoway.com.br>
=> Remove IFS variable support.

.travis.yml, cmd/nash/Makefile, internal/sh/shell_test.go, parser/parse.go, parser/parse_test.go, spec.ebnf
Add the last missing syntax construct for functions:
```sh
fn a() {
return "1"
}
fn b() {
return a()
}
```
=> Add support for fncall in return

internal/sh/shell.go, internal/sh/shell_test.go
- Refactored 'initEnv' to accept '=' signs in environment variable values;
- Added new test for initEnv.
=> Fixed 'initEnv' for variables with '=' sign

.travis.yml, cmd/nash/Makefile, cmd/nash/main.go, internal/sh/shell.go, internal/sh/shell_test.go, nash.go
This PR got a little too long because In order to fix #62 I had to implement #151 first. Then as discussed in #150 I had to guarantee that `bindfn` would be disabled in non-interactive (script) mode before I could implement the binds precedence over commands.
Fixes #62 .
Closes #151 .
Closes #150 .
=> Disable bindfn in non-interactive mode. 

.gitignore, cmd/nash/main.go, nash.go
Not sure if this is a great idea, but I was needing to call nash scripts from Go code, and my scripts take command line args. Checking out the current code I was unable a way to do so, but I found out code on the main package that did it and basically moved it. Probably not on the best way possible. Please advise :-)
=> Add shell.ExecFileArgs

cmd/nash/vendor.sh
@tiago4orion The build is breaking when I run vendor...but it also breaks with the same error if I run the old original script, not sure of what went wrong. The error:
```
github.com/NeowayLabs/nash (download)
github.com/chzyer/readline (download)
github.com/NeowayLabs/nash/token
github.com/NeowayLabs/nash/sh
github.com/chzyer/readline
github.com/NeowayLabs/nash/scanner
github.com/NeowayLabs/nash/ast
github.com/NeowayLabs/nash/errors
github.com/NeowayLabs/nash/parser
github.com/NeowayLabs/nash/internal/sh
github.com/NeowayLabs/nash
_/home/katcipis/workspace/go/src/github.com/NeowayLabs/nash/cmd/nash
./completer.go:34: c.term.PauseRead undefined (type *readline.Terminal has no field or method PauseRead)
exit status 2
```
The vendor directory does not contain the readline project …
=> Update vendor script to not use IFS

ast/node.go, ast/node_fmt.go, internal/sh/shell.go, internal/sh/shell_test.go, parser/parse.go, parser/parse_test.go, scanner/lex.go, scanner/lex_test.go
Add missing support to update list entries:
Examples of usage:
```sh
a = (0 1 2 3 4 5)
a[0] = "666"
i = "2"
a[$i] = "666"
a[0] <= ls /
a[1] <= echo -n "hello world"
```
Closes #163 
Signed-off-by: Tiago <tiago.natel@neoway.com.br>
=> fix missing support for list update

ast/node.go, ast/node_args.go, ast/node_fmt.go, internal/sh/shell.go, internal/sh/shell_test.go, parser/parse.go, parser/parse_test.go, scanner/lex_test.go
Enables:
```sh
for i in getfiles("/") {
}
```
and 
```sh
for i in (1 2 3 4 5) {
}
```
=> Advanced for ranges

hack/check.sh
Enables `make test` using enzo's `ls` **and** the GNU version..
=> enzo's ls doesn't support file listings

internal/sh/shell.go, internal/sh/shell_test.go
This is kind of shitty for now. But it fixes the problem.
The tests had to be refactored because of race conditions, but I don't know if it's the right solution.
Also, I had to leave the `SetStdout` call in `executeCommand` because `cmd.StdoutPipe()` is already setting Stdout :disappointed:. Any ideas?
Fixes #210
=> Refactor getCommand to set stuff needed by pipe commands.

internal/sh/shell_test.go, parser/parse.go, parser/parse_test.go, scanner/lex_test.go, spec.ebnf
The code below now is valid:
ids_luns <= append($ids_luns, ($id $lun))
Closes #214 
Signed-off-by: Tiago Natel de Moura <tiago.natel@neoway.com.br>
=> Add support for list literals at function call.

ast/node.go, ast/node_args.go, ast/node_fmt.go, ast/nodetype_string.go, internal/sh/builtin.go, internal/sh/builtin/append.go, internal/sh/builtin/append_test.go, internal/sh/builtin/chdir.go, internal/sh/builtin/exit.go, internal/sh/builtin/format.go, internal/sh/builtin/glob.go, internal/sh/builtin/len.go, internal/sh/builtin/loader.go, internal/sh/builtin/print.go, internal/sh/builtin/split.go, internal/sh/cmd.go, internal/sh/fncall.go, internal/sh/shell.go, internal/sh/shell_test.go, nash_test.go, parser/parse.go, parser/parse_regression_test.go, parser/parse_test.go, scanner/lex.go, scanner/lex_test.go, sh/shell.go, spec.ebnf, token/token.go
The '...' syntax was added to declare functions that can receive any number of arguments. 
- A ... parameter is received as a list inside the function.
```sh
fn println(args...) {
for a in $args {
print($a)
}
print("\n")
}
```
- A ... parameter is optional
```sh
println() # Output: \n
fn a(b, c...) {
print($b, $c...)
}
a("test") # Output: test
a() # Fail, requires at least one argument.
```
- As a special case, the ... expansion is allowed in command arguments to pass a list as multiples arguments.
```sh
curl $args
curl $args...
```
This is only a first proposal, feel free to criticize.
I believe now we can change the `print` builtin to just print (no format) and then add the following functions as nash stdlib:
```sh
fn printf(fmt, args...) {
print(format(fmt, $args...))
}
fn …
```
=> Add support for variadic arguments

Makefile, stdbin/mkdir/main.go, stdbin/mkdir/mkdir_test.go
This PR starts a long road to address #230. 
As I'm using a lot of windows nowadays... I'll start scratching my itches, by adding the programs I'm missing in windows. The work for the stdbin build system and integrated tests could come up in another PR.
Another PR could be created to copy our programs from c0defellas/enzo to here also.
p.s.: the name of the branch is `add-stdbin-pwd` because `pwd` was my initial target for this development, but soon realized I was unable to create the stdbin directory in windows without _right-click in explorer_ ... Then mkdir priority escalated very fast =P
=> stdbin: adding mkdir

internal/sh/builtin/glob.go, internal/sh/builtin/glob_test.go
The current glob implementation generates a fatal error if the pattern passed is invalid. This is not a great idea since glob is a builtin and taking the decision to abort or not from the programmer for such an essencial/basic function does not seem very smart.
I realized that when I was trying to generalize a function to expand args with glob, a very easy solution for me is to try to glob all parameters, the ones that succeed I use the results, the ones that don't I use the original parameter. The only problem is that some parameters will force my scripts to abort =( (for something that is a recoverable error).
=> Add second return to glob to indicate pattern error

.travis.yml, internal/sh/builtin/chdir.go, internal/sh/functions_test.go, internal/sh/shell.go, internal/sh/shell_test.go
Fix bindfn vargs to work properly, there was some validations that where unecessary so I removed them and fixed the cd builtin bindfn so it keeps working. Not sure if it was the best course of action but it seemed that the duplicated validations of function arity where not the way to go (that is already handled on the function dispatch mechanism).
Also changed travis to only work with Go >= 1.9 since the t.Helper() thing was really helpfull debugging test failures =)
Anyway, nothing better to start an year than crappy code
=> Fix bindfn vargs

internal/sh/shell_test.go, nash_test.go, spec_test.go, tests/cfg.go, tests/internal/tester/tester.go, tests/listindex_test.go, tests/stringindex_test.go
@katcipis I know the tests package are there for blackbox tests, but I think it's a good place to put some of the common/util logics that were currently repeated in test code (like getting gopath, testdir, nashcmd).
What do you think?
Closes #255
=> add common cfg into tests pkg and simplify setup of tests

internal/sh/shell_linux_test.go
Improves detection if user namespaces are allowed on linux and skip tests if not.
Closes #252
=> Fix userns permission checking

.gitignore, Makefile, stdbin/strings/main.go, stdbin/strings/strings.go, stdbin/strings/strings_test.go
Inspired on what I read about the "strings" exec on the book The Practice of Programming.
I think we can achieve something that has one parameter...the word size...instead of this:
https://sourceware.org/binutils/docs-2.23/binutils/strings.html
Things like "target" makes no sense to me...why not just print every stream of printable characters found ? It is how it is implemented on the book and I liked it =D
=> Add strings to stdbin

cmd/nash/cli.go
A lot of times I shot myself on the foot being unable to start terminals on taowm and rio and not knowing why they where not loading (could be a lot of different things) but was actually some error loading my nash init.sh. It seems better to drop the user on a default prompt so he can fix any kind of mistake instead of just exiting the process (which causes the entire terminal to close).
=> print init loading fatal error instead of exiting

internal/sh/shell.go, internal/sh/shell_import_test.go, internal/sh/shell_test.go, nash.go
Instead of aborting just print error messages on the shell stderr so the user dont go completely blind without an stdlib.
=> Dont abort on invalid NASHPATH/NASHROOT

cmd/nash/install.go, cmd/nash/install_test.go, internal/sh/shell.go, internal/sh/shell_import_test.go, internal/sh/shell_test.go, internal/sh/util_test.go, internal/testing/fixture/io.go, nash.go, nash_test.go
On OSX, the directories /tmp and /var are symlinks to
/private/tmp and /private/var respectively.
This change adds an additional call to filepath.EvalSymlinks
before using paths obtained by TempDir.
Also, this change identified a problem related to logging of
the warnings when nashpath and/or nashroot aren't properly set.
As there are tests that do instantiate nash with wrong directories
for testing, this was making a mess in the stderr of the tests
because now nash doesn't abort in case of errors. This change address that too. (Maybe not in the best way)
Signed-off-by: Tiago de Bem <tiago.moura@nginx.com>
=> OSX symlinks for /tmp and /var break the tests

.travis.yml
I was taking a look on the Travis files...and now it actually seems that we don't have CI anymore, did we remove it ? (don't remember that). We probably lost it when we moved the projects across groups...I think :-)
=> Update Tiago Natel email

cmd/nash/completer.go, internal/sh/shell.go, nash.go
Not sure if exposing a Log method is the best way to go, but wanted to respect the debug configuration.
=> Improve logging on Completer
